feat: create config file for welcome bot (#649)
systers/portal pull request #690
Opened 2020-10-24 08:51 UTC by m-code12

### Description
Created config.yml file for the welcome bot to help first-time contributors. To activate the app you need to go to https://github.com/apps/welcome and click on install and give the app the required permissions.( Can only be done by a member of the org)

Fixes #649 

### Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
[x] Bug fix (non-breaking change which fixes an issue)
[x] New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I have tested the welcome bot with the same config.yml file in my personal repository. Here is a link to the repo:
https://github.com/m-code12/WelcomeBot

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-10-30 16:58 UTC, sakshi1499 requested changes

2020-10-30 16:58 UTC, sakshi1499 commented on .github/config.yml
> +  Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey  ahead 🚀.
Extra space between journey and ahead

2020-10-30 16:58 UTC, sakshi1499 commented on .github/config.yml
> +  Thank you and congrats🎉 for opening your first pull request.✨ AnitaB.org is an inclusive community, committed to creating a safe and positive environment.🌸Please adhere to our [Code of Conduct](htt
Here there is a full stop before and after the emoji. Can you remove it from one place.

2020-10-30 16:58 UTC, sakshi1499 commented on .github/config.yml
> +  Thank you and congrats🎉 for opening your first pull request.✨ AnitaB.org is an inclusive community, committed to creating a safe and positive environment.🌸Please adhere to our [Code of Conduct](htt
Please also add about Commit Guidelines as most new comers face that issue. You can find the link to the same in wiki.

2020-11-05 06:09 UTC, sakshi1499 commented
@m-code12 Are you working on it?

2020-11-05 06:34 UTC, m-code12 commented
@sakshi1499 I have got caught up with my exams. Please could you give me some time to complete it?

2020-11-05 06:39 UTC, sakshi1499 commented
100% @m-code12 . Its recommended to revert back in 3-4 days, so that we know you are active. You could check back in and just say you are busy. Moreover the PR seems fine too, just minor changes 💯

2020-11-12 07:03 UTC, m-code12 commented
@sakshi1499 
I have made the changes. Do have a look.

2020-11-15 10:31 UTC, m-code12 commented
@sakshi1499 Could you please review and merge this pr.

2020-11-24 15:00 UTC, m-code12 commented
> @sakshi1499 Could you please review and merge this pr?

@sakshi1499

2020-11-27 15:50 UTC, sakshi1499 approved these changes
Great work! Looking for another approval and then I'll merge it 💯

2020-12-07 06:42 UTC, merged